#!/usr/bin/env ruby
require 'xcodeproj'

def fail_with(message)
  STDERR.puts "Error: #{message}"
  exit 1
end

# Generate AppDelegate.mm with auto-discovered test functions
def generate_app_delegate(output_path, test_files)
  test_names = test_files.map { |f| File.basename(f, '.cpp') }
  extern_declarations = test_names.map { |name| "extern int #{name}_main();" }.join("\n")
  test_calls = test_names.map { |name| "        #{name}_main();" }.join("\n")

  app_delegate_content = <<~OBJC
    // AUTO-GENERATED by setup_project.rb - DO NOT EDIT MANUALLY
    // This file is regenerated on each test run with discovered test files

    #import "AppDelegate.h"
    #import <sys/resource.h>
    #import <unistd.h>

    #{extern_declarations}

    @implementation AppDelegate

    - (void)copyModelFromBundle:(NSString *)bundlePath toDocuments:(const char *)modelDir {
        if (!modelDir) return;

        NSFileManager *fileManager = [NSFileManager defaultManager];
        NSString *modelName = [NSString stringWithUTF8String:modelDir];
        NSString *sourceModelPath = [NSString stringWithFormat:@"%@/%@", bundlePath, modelName];

        if ([fileManager fileExistsAtPath:modelName]) {
            [fileManager removeItemAtPath:modelName error:nil];
        }

        [fileManager copyItemAtPath:sourceModelPath toPath:modelName error:nil];
    }

    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
        NSString *documentsDirectory = paths[0];
        chdir([documentsDirectory UTF8String]);

    #if !TARGET_OS_SIMULATOR
        freopen("cactus_test.log", "w", stdout);
        freopen("cactus_test.log", "a", stderr);
        setbuf(stdout, NULL);
        setbuf(stderr, NULL);
    #endif

        struct rlimit limit = {4096, 4096};
        setrlimit(RLIMIT_NOFILE, &limit);

        NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
        [self copyModelFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_MODEL")];
        [self copyModelFromBundle:bundlePath toDocuments:getenv("CACTUS_TEST_TRANSCRIBE_MODEL")];

        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    #{test_calls}
            exit(0);
        });

        return YES;
    }

    - (UISceneConfiguration *)application:(UIApplication *)application configurationForConnectingSceneSession:(UISceneSession *)connectingSceneSession options:(UISceneConnectionOptions *)options {
        return [[UISceneConfiguration alloc] initWithName:@"Default Configuration" sessionRole:connectingSceneSession.role];
    }

    - (void)application:(UIApplication *)application didDiscardSceneSessions:(NSSet<UISceneSession *> *)sceneSessions {}

    @end
  OBJC

  File.write(output_path, app_delegate_content)
  puts "Generated AppDelegate.mm with #{test_names.length} test(s)"
end

# Environment variables
project_root = ENV['PROJECT_ROOT']
tests_root = ENV['TESTS_ROOT']
cactus_root = ENV['CACTUS_ROOT']
project_path = ENV['XCODEPROJ_PATH']

fail_with("PROJECT_ROOT not set") unless project_root
fail_with("TESTS_ROOT not set") unless tests_root
fail_with("CACTUS_ROOT not set") unless cactus_root
fail_with("XCODEPROJ_PATH not set") unless project_path
fail_with("Xcode project not found") unless File.exist?(project_path)

project = Xcodeproj::Project.open(project_path) rescue fail_with("Failed to open Xcode project")
target = project.targets.first or fail_with("No targets found")

# Add test files
tests_group = project.main_group.find_subpath('Tests', true)
tests_group.set_path(tests_root)
tests_group.set_source_tree('<absolute>')

discovered_test_files = Dir.glob(File.join(tests_root, 'test_*.cpp'))
  .reject { |f| File.basename(f) == 'test_utils.cpp' }
  .sort
  .map { |f| File.basename(f) }

puts "Discovered #{discovered_test_files.length} test file(s):"
discovered_test_files.each { |f| puts "  - #{f}" }

test_files = {}
discovered_test_files.each { |f| test_files[f] = "#{File.basename(f, '.cpp')}_main" }
test_files['test_utils.cpp'] = nil

test_files.each do |filename, renamed_main|
  file_path = File.join(tests_root, filename)
  next unless File.exist?(file_path)
  existing = tests_group.files.find { |f| f.path == filename || f.real_path&.to_s == file_path }
  file_ref = existing || begin
    ref = tests_group.new_reference(file_path)
    ref.set_source_tree('<absolute>')
    ref
  end
  build_file = target.source_build_phase.files.find { |bf| bf.file_ref == file_ref }
  build_file ||= target.source_build_phase.add_file_reference(file_ref)
  build_file.settings = { 'COMPILER_FLAGS' => "-Dmain=#{renamed_main}" } if renamed_main
end

unless tests_group.files.any? { |f| f.path == 'test_utils.h' }
  ref = tests_group.new_reference(File.join(tests_root, 'test_utils.h'))
  ref.set_source_tree('<absolute>')
end

generate_app_delegate(File.join(File.dirname(project_path), 'CactusTest', 'AppDelegate.mm'), discovered_test_files)

# Clean up old CactusSources group
cactus_sources_group = project.main_group.groups.find { |g| g.name == 'CactusSources' }
if cactus_sources_group
  cactus_sources_group.files.each do |f|
    bf = target.source_build_phase.files.find { |b| b.file_ref == f }
    target.source_build_phase.files.delete(bf) if bf
  end
  cactus_sources_group.clear
  cactus_sources_group.remove_from_project
end

# Add cactus source files
cactus_sources_group = project.main_group.new_group('CactusSources')
cactus_sources_group.set_source_tree('<group>')

['engine', 'graph', 'kernel', 'ffi', 'models'].each do |dir|
  Dir.glob(File.join(cactus_root, dir, '*.cpp')).each do |src_file|
    next if cactus_sources_group.files.any? { |f| f.real_path&.to_s == src_file }
    file_ref = cactus_sources_group.new_reference(src_file)
    file_ref.set_source_tree('<absolute>')
    target.source_build_phase.add_file_reference(file_ref)
  end
end

# Configure build settings
target.build_configurations.each do |config|
  config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
  [tests_root, cactus_root, *%w[graph engine kernel ffi models].map { |d| File.join(cactus_root, d) }].each do |path|
    config.build_settings['HEADER_SEARCH_PATHS'] << path unless config.build_settings['HEADER_SEARCH_PATHS'].include?(path)
  end

  config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
  config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'

  # Compiler flags
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']

  # Platform defines
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DPLATFORM_CPU_ONLY=1'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-D__ARM_NEON=1'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-D__ARM_FEATURE_FP16_VECTOR_ARITHMETIC=1'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-D__ARM_FEATURE_DOTPROD=1'

  # Threading and warning flags
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-pthread'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wall'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wextra'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-pedantic'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-c++20-designator'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-missing-field-initializers'

  # Architecture and optimization flags
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-march=armv8.2-a+fp16+simd+dotprod'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-O3'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DNDEBUG'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-fomit-frame-pointer'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-funroll-loops'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-ftree-vectorize'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-fvisibility=hidden'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-fvisibility-inlines-hidden'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-ffunction-sections'
  config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-fdata-sections'

  # Linker flags
  config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
  config.build_settings['OTHER_LDFLAGS'] << '-Wl,-dead_strip'
  config.build_settings['OTHER_LDFLAGS'] << '-flto'

  # Enable Link Time Optimization
  config.build_settings['LLVM_LTO'] = 'YES'
end

project.save rescue fail_with("Failed to save Xcode project")
